### ISSUE TITLE
Component superclass interface mapping

### ISSUE THREAD

**Issue by miche-atucha** [bridje/bridje-framework#10]
_**Given:**_
Interfaz X
Class Y implements X
Component Z extends Y
_**On:**_
Ioc.context().findAll(X.class);
_**Result:**_
returns empty array.
_**Expected result:**_
returns [Z]

**Comment by gilbertovento** [comment]
Fixed in [225c6944bbc622f365fd4d480a5e43ae4e2f9375](https://github.com/bridje/bridje-framework/commit/225c6944bbc622f365fd4d480a5e43ae4e2f9375)
