### ISSUE TITLE
init server in http

### ISSUE THREAD

**Issue by miche-atucha** [bridje/bridje-framework#39]
Now i have to:
- mount etc folder with vfs service.
- start the server.

I would like to do this (or something like this):
`HttpServer.usingEtc('/path/to/etc').start();`
The http takes care of vfs system in background. This way i think is easier.

**Comment by gilbertovento** [comment]
This maybe cannot be done becouse the mount concept is not from the http server, and it cannot be monopolise by it, the user needs to put the configuration for the etc in his main class, but i can maybe put some shortcuts to it in the Vfs api. Ill check this out for the next version.

**Comment by gilbertovento** [comment]
The VfsService now have some utility methods to help with the initial configuration.
