### ISSUE TITLE
Context Listener

### ISSUE THREAD

**Issue by gilbertovento** [bridje/bridje-framework#4]
Add context listener

**Comment by gorums** [comment]
Defined what the contextListener purpose

**Comment by gilbertovento** [comment]
The context listener will be any component that implements the interface ContextListener, the framework must search all ContextListener implementations via the standard way of components resolution and call the 3 methods of the interface in the propper place, the methods will be

preCreateComponent: will be called before a component is created.
preInitComponent: after the component has been instantiate and before injecting the components dependencies
postInitComponent: after the components dependencies injection.
