### ISSUE TITLE
handler priority in http

### ISSUE THREAD

**Issue by miche-atucha** [bridje/bridje-framework#40]
the root handler component of http server has priority `0`, so if i implements a handler with priority lower than `0`, is never called.
so, why not this root handler of http has `Integer.MIN_VALUE` instead than `0`?

**Comment by gilbertovento** [comment]
It may be done, not problem. last time i try to made it i was having a problemn becouse i try to put this value, Integer.MIN_VALUE + 100, and it give me an error, but i will see into it for the next version.

**Comment by gilbertovento** [comment]
Done
