### ISSUE TITLE
Replace the regular expressions querys in the VFS.

### ISSUE THREAD

**Issue by gilbertovento** [bridje/bridje-framework#43]
The functions listFolders and listFiles in the VfsService and VfsResource requires that the user pass a regex to it, The regex could be replaced with a more standard way of serach in a file tree, The needed wilcard characters are.

* \* - cero or more characters except for \\
* ? - a single character except for \\
* \*\* - cero or more characters including \\

**Comment by miche-atucha** [comment]
resolved
